from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor


def generate_pdf(
    filename,
    customer_data,
    prediction,
    probability,
    confidence,
    revenue_at_risk,
    monthly_charge,
    total_charges
):
    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.textColor = HexColor("#2563EB")

    heading_style = styles["Heading2"]

    normal_style = styles["BodyText"]

    doc = SimpleDocTemplate(filename)

    elements = []

    # ==========================
    # Title
    # ==========================

    elements.append(
        Paragraph(
            "Customer Retention Intelligence Platform",
            title_style
        )
    )

    elements.append(
        Paragraph(
            "Customer Prediction Report",
            heading_style
        )
    )

    elements.append(Spacer(1, 20))

    # ==========================
    # Customer Information
    # ==========================

    elements.append(
        Paragraph(
            "<b>Customer Information</b>",
            heading_style
        )
    )

    for key, value in customer_data.items():
        elements.append(
            Paragraph(
                f"<b>{key}</b>: {value}",
                normal_style
            )
        )

    elements.append(Spacer(1, 20))

    # ==========================
    # Prediction
    # ==========================

    result = "Churn" if prediction == 1 else "Stay"

    elements.append(
        Paragraph(
            "<b>Prediction Result</b>",
            heading_style
        )
    )

    elements.append(
        Paragraph(
            f"Prediction : {result}",
            normal_style
        )
    )

    elements.append(
        Paragraph(
            f"Probability : {probability*100:.2f}%",
            normal_style
        )
    )

    elements.append(
        Paragraph(
            f"Confidence : {confidence*100:.2f}%",
            normal_style
        )
    )

    elements.append(Spacer(1, 20))

    # ==========================
    # Revenue Analytics
    # ==========================

    elements.append(
        Paragraph(
            "<b>Revenue Analytics</b>",
            heading_style
        )
    )

    elements.append(
        Paragraph(
            f"Monthly Revenue : ₹{monthly_charge:.2f}",
            normal_style
        )
    )

    elements.append(
        Paragraph(
            f"Revenue at Risk : ₹{revenue_at_risk:.2f}",
            normal_style
        )
    )

    elements.append(
        Paragraph(
            f"Customer Lifetime Value : ₹{total_charges:.2f}",
            normal_style
        )
    )

    elements.append(Spacer(1, 20))

    # ==========================
    # Recommendation
    # ==========================

    elements.append(
        Paragraph(
            "<b>Business Recommendation</b>",
            heading_style
        )
    )

    if prediction == 1:

        recommendation = """
        Contact the customer immediately.
        Offer loyalty discounts.
        Suggest yearly contract.
        Provide free technical support.
        """

    else:

        recommendation = """
        Offer premium plans.
        Reward customer loyalty.
        Cross-sell additional services.
        """

    elements.append(
        Paragraph(
            recommendation,
            normal_style
        )
    )

    elements.append(Spacer(1, 30))

    elements.append(
        Paragraph(
            "Generated by Customer Retention Intelligence Platform",
            normal_style
        )
    )

    doc.build(elements)